version: '3'

services:
  postfix:
    image: eeacms/postfix
    container_name: postfix
    environment:
      - MTP_HOST=foo.com
      
  busybox-shell:
    image: busybox
    stdin_open: true
    tty: true
    links:
      - postfix
    command: sh